default_stages:
  - pre-push
repos:
-   repo: https://github.com/pylint-dev/pylint
    rev: v3.3.6
    hooks:
    -   id: pylint
        files: libraries
        language: python
        args: [--rcfile=.pylintrc]
        verbose: true
